"""In-process XMPP mock for bridge scenario tests.

The real bridge.py runs as a subprocess and connects here over STARTTLS +
SCRAM-SHA-1 (with PK_XMPP_NO_VERIFY=1 because the cert is self-signed). The
mock mirrors a minimal prosody-like server:

    stream -> features(starttls) -> proceed -> TLS
    -> stream -> features(SCRAM-SHA-1) -> auth -> challenge -> response
    -> verify proof -> success -> stream -> features(bind)
    -> bind iq -> jid result -> presence

Then behavior differs by mode:
  * ``inbound``: pushes one chat message and captures whether SCRAM verified
                 and whether the bind iq arrived.
  * ``send``:    waits for an outgoing <message> stanza and captures it.

The server binds an ephemeral port; certificate/key are generated by the test
fixture (self-signed) and loaded here.
"""

import base64
import hashlib
import hmac
import socket
import ssl
import threading
import time

NS_CLIENT = "jabber:client"
NS_STREAM = "http://etherx.jabber.org/streams"
NS_TLS = "urn:ietf:params:xml:ns:xmpp-tls"
NS_SASL = "urn:ietf:params:xml:ns:xmpp-sasl"
NS_BIND = "urn:ietf:params:xml:ns:xmpp-bind"
USER = "user"
PASSWORD = "pencil"


def server_scram(password, c_first, client_nonce):
    server_nonce = client_nonce + "SERVNONCE"
    salt = b"mock-salt-1234"
    iterations = 4096
    server_first = "r=%s,s=%s,i=%d" % (
        server_nonce, base64.b64encode(salt).decode(), iterations)
    salted = hashlib.pbkdf2_hmac("sha1", password.encode(), salt, iterations)
    client_key = hmac.new(salted, b"Client Key", hashlib.sha1).digest()
    stored_key = hashlib.sha1(client_key).digest()
    c_final_no_proof = "c=biws,r=%s" % server_nonce
    auth = c_first + "," + server_first + "," + c_final_no_proof
    client_sig = hmac.new(stored_key, auth.encode(), hashlib.sha1).digest()
    expected_proof = bytes(a ^ b for a, b in zip(client_key, client_sig))
    server_key = hmac.new(salted, b"Server Key", hashlib.sha1).digest()
    server_sig = hmac.new(server_key, auth.encode(), hashlib.sha1).digest()
    return server_first, expected_proof, server_sig


def _recv_until(conn, marker):
    buf = b""
    while marker not in buf:
        chunk = conn.recv(4096)
        if not chunk:
            break
        buf += chunk
    return buf


def _recv_tag(conn, tag):
    buf = b""
    close_self, close_full = b"/>", b"</" + tag.encode() + b">"
    while close_self not in buf and close_full not in buf:
        chunk = conn.recv(4096)
        if not chunk:
            break
        buf += chunk
    return buf


class XMPPMock:
    def __init__(self, certfile, keyfile, mode="inbound"):
        self.certfile = certfile
        self.keyfile = keyfile
        self.mode = mode
        self.error = None
        self.scram_verified = None
        self.plain_verified = None
        self.received_bind = None
        self.received_message_stanza = None
        self._srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self._srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        self._srv.bind(("127.0.0.1", 0))
        self._srv.listen(1)
        self.host, self.port = self._srv.getsockname()
        self._thread = threading.Thread(target=self._serve, daemon=True)

    def start(self):
        self._thread.start()
        return self

    def stop(self):
        try:
            self._srv.close()
        except Exception:
            pass

    def _serve(self):
        try:
            conn, _ = self._srv.accept()
        except Exception:
            return
        try:
            self._handle(conn)
        except Exception as exc:  # capture unexpected server-side errors
            self.error = repr(exc)
        finally:
            try:
                conn.close()
            except Exception:
                pass

    def _handle(self, conn):
        # 1) first stream + features with starttls
        _recv_until(conn, b">")
        conn.sendall(
            b"<?xml version='1.0'?><stream:stream xmlns='jabber:client' "
            b"xmlns:stream='http://etherx.jabber.org/streams' id='mock' version='1.0'>"
            b"<stream:features><starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'/></stream:features>"
        )
        # 2) client requests starttls
        _recv_tag(conn, "starttls")
        conn.sendall(b"<proceed xmlns='urn:ietf:params:xml:ns:xmpp-tls'/>")
        ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
        ctx.load_cert_chain(self.certfile, self.keyfile)
        conn = ctx.wrap_socket(conn, server_side=True)
        # 3) restarted stream + features with SASL mechanism
        _recv_until(conn, b">")
        if self.mode == "plain":
            mech = b"<mechanism>PLAIN</mechanism>"
        else:
            mech = b"<mechanism>SCRAM-SHA-1</mechanism>"
        conn.sendall(
            b"<stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' id='mock2' version='1.0'>"
            b"<stream:features><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>"
            + mech + b"</mechanisms></stream:features>"
        )
        # 4) SASL auth
        auth = _recv_tag(conn, "auth")
        auth_payload = base64.b64decode(auth.split(b">")[1].split(b"<")[0]).decode()
        if self.mode == "plain":
            # PLAIN: \0user\0password, single round trip then success.
            fields = auth_payload.split("\0")
            self.plain_verified = (
                len(fields) == 3 and fields[1] == USER and fields[2] == PASSWORD
            )
            conn.sendall(
                b"<success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'/>"
            )
        else:
            client_first = auth_payload
            c_first_bare = client_first[3:]
            client_nonce = [p for p in c_first_bare.split(",") if p.startswith("r=")][0][2:]
            server_first, expected_proof, server_sig = server_scram(
                PASSWORD, c_first_bare, client_nonce)
            conn.sendall(
                b"<challenge xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>"
                + base64.b64encode(server_first.encode()) + b"</challenge>"
            )
            resp = _recv_tag(conn, "response")
            payload = base64.b64decode(resp.split(b">")[1].split(b"<")[0]).decode()
            proof = [p for p in payload.split(",") if p.startswith("p=")][0][2:]
            self.scram_verified = base64.b64decode(proof) == expected_proof
            conn.sendall(
                b"<success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>"
                + base64.b64encode(b"v=" + base64.b64encode(server_sig)) + b"</success>"
            )
        # 5) restarted stream + bind
        _recv_until(conn, b">")
        conn.sendall(
            b"<stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' id='mock3' version='1.0'>"
            b"<stream:features><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'/></stream:features>"
        )
        bind = _recv_tag(conn, "iq")
        self.received_bind = b"type='set'" in bind
        conn.sendall(
            b"<iq type='result' id='pk-bind'><bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'>"
            b"<jid>user@localhost/phonekit</jid></bind></iq>"
        )
        if self.mode in ("inbound", "plain"):
            _recv_tag(conn, "presence")
            conn.sendall(
                b"<message type='chat' from='friend@localhost' to='user@localhost'>"
                b"<body>hello from the mock server</body></message>"
            )
            time.sleep(1)
        else:
            msg = _recv_tag(conn, "message")
            self.received_message_stanza = msg
            time.sleep(1)